services:
  db:
    build: ./postgres
    restart: always
    # ports:
      # - "5432:5432"
    # networks:
    #   - default

  zookeeper:
    restart: always
    image: wurstmeister/zookeeper
    container_name: zookeeper
    # ports:
      # - "2181:2181"
  kafka:
    restart: always
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    # ports:
      # - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  

  go-backend:
    restart: always
    depends_on:
      - kafka
      - db
    build: .
    ports:
      - "8000:8000"
    # networks:
    #   - default
  
  go-msg-handler:
    restart: always
    build: ./msg_handler
    depends_on:
      - kafka
      - go-backend
    